name: dynamicbind
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  # Python
  - python=3.11

  # PyTorch Stack from the 'pytorch' channel
  - pytorch::pytorch=2.3.0
  - pytorch::pytorch-cuda=12.1

  # Other packages from 'conda-forge'
  - conda-forge::rdkit
  - conda-forge::scikit-learn
  - conda-forge::pandas
  - conda-forge::matplotlib
  - conda-forge::biopython
  - conda-forge::ipykernel
  
  # Pip for the PyG stack
  - pip
  - pip:
    - torch_geometric
    - torch_cluster
    - torch_scatter
    - torch_sparse
    - e3nn
    - fair-esm
    - spyrmsd
    # This special source-finding flag must be the last item in the pip list
    - --find-links https://data.pyg.org/whl/torch-2.3.0+cu121.html

variables:
  # This solves the original MKL threading error
  MKL_THREADING_LAYER: GNU
